##Systems
System::JobProcessorWorker:
  queue: high
  cron: '0 */5 * * * *'

## destroy some data
System::DatabaseCleanerWorker:
  queue: low
  cron: '0 2 * * *'

## Zoho CRM sync
System::ZohoCrmSynchronizerWorker:
  queue: high
  cron: '0 1 1 * *'

## Miscelaneous workers
RefreshDashboardStatisticsWorker:
  queue: default
  cron: '*/5 * * * *'
InitializePeriodsWorker:
  queue: low
  cron: '0 3 1 * *'
Subscription::StatisticsWorker:
  queue: default
  cron: '0 5 * * *'
Order::RemindToNewKitWorker:
  queue: high
  cron: '15 3 1 12 *'

## Billing
BillingMod::CreateInvoiceWorker:
  queue: low
  cron: '15 0 1 * *'
BillingMod::PrepareBillingsWorker:
  queue: low
  cron: '0 15 * * *'

## Notifications worker
Notifications::DocumentWorker:
  queue: default
  cron: '0 8 * * *'
Notifications::RetrieversWorker:
  queue: default
  cron: '0 8 * * *'
Notifications::ScansNotDeliveredNotificationWorker:
  queue: default
  cron: '0 1 * * *'
# Notifications::PaperQuotaReachedWorker:
#   queue: default
#   cron: '0 8 * * *'
Notifications::PublishedDocumentDailyWorker:
  queue: default
  cron: '0 8 * * *'
Notifications::PreAssignmentDeliveryDailyWorker:
  queue: default
  cron: '0 8 * * *'
Notifications::PreAssignmentExportWorker:
  queue: default
  cron: '0 8 * * *'
Notifications::ProcessedRequestsWorker:
  queue: default
  cron: '0 8 * * *'



## Accounting Plan worker

AccountingPlan::IbizaUpdateWorker:
  queue: low
  cron: '0 4 * * *'

# AccountingPlan::ExactOnlineUpdateWorker:
  # queue: default
  # cron: '0 3 * * *'

AccountingPlan::MyUnisoftUpdateWorker:
  queue: low
  cron: '0 5 * * *'

AccountingPlan::SageGecUpdateWorker:
  queue: low
  cron: '0 6 * * *'

## Budgea retrievers workers

DataProcessor::OperationsWorker:
  queue: default
  cron: '*/10 * * * * *'

DataProcessor::McfWorker:
  queue: low
  cron: '0 */15 * * * *'

## Accounting flow workers

Ftp::FetcherWorker:
  queue: low
  cron: '0 */30 * * * *'

RetrieveEmailedDocumentWorker:
  queue: default
  cron: '30 */6 * * * *'


## File import

FileImport::DropboxWorker:
  queue: file_import
  cron: '0 */8 * * * *'

FileImport::IbizaboxWorker:
  queue: file_import
  cron: '30 */11 * * * *'

FileImport::SftpFromAllWorker:
  queue: file_import
  cron: '0 15 */6 * * *'

FileImport::FtpFromAllWorker:
  queue: file_import
  cron: '0 30 */6 * * *'

RetrieveOcrProcessedDocumentWorker:
  queue: high
  cron: '*/10 * * * * *'

PublishDocumentWorker:
  queue: low
  cron: '*/2 * * * * *'


## Pre assignment builder & delivery

PreAssignment::Builder::IbizaWorker:
  queue: default
  cron: '*/10 * * * * *'

# PreAssignment::Builder::ExactOnlineWorker:
  # queue: high
  # cron: '*/10 * * * * *'

PreAssignment::Builder::MyUnisoftWorker:
  queue: default
  cron: '*/10 * * * * *'

PreAssignment::Builder::SageGecWorker:
  queue: default
  cron: '*/10 * * * * *'

PreAssignment::Delivery::IbizaWorker:
  queue: default
  cron: '*/10 * * * * *'

# PreAssignment::Delivery::ExactOnlineWorker:
  # queue: high
  # cron: '*/10 * * * * *'

PreAssignment::Delivery::MyUnisoftWorker:
  queue: default
  cron: '*/10 * * * * *'

PreAssignment::Delivery::SageGecWorker:
  queue: default
  cron: '*/10 * * * * *'


## Daily data verifier worker
DataVerificator::DailyDataVerifierWorker:
  queue: high
  cron: '0 3 * * *'

## Staffing flows

Staffingflow::GroupingWorker:
  queue: low
  cron: '*/20 * * * * *'

Staffingflow::PreassignmentWorker:
  queue: default
  cron: '*/20 * * * * *'

Staffingflow::JefactureWorker:
  queue: default
  cron: '*/20 * * * * *'

Staffingflow::SendPreAssignmentNeededWorker:
  queue: high
  cron: '0 */5 * * * *'

Staffingflow::SendBundleNeededWorker:
  queue: high
  cron: '0 */5 * * * *'

## Archive resend document corrupted

Archive::ResendDocumentCorruptedWorker:
  queue: low
  cron: '0 0 */1 * * *'

## Delivery workers

DeliverFileToDropbox: &deliver_file_defaults
  class: FileDelivery::DeliverFileWorker
  queue: file_delivery
  cron: '*/10 * * * * *'
  args: dbb
DeliverFileToDropboxExtended:
  <<: *deliver_file_defaults
  args: dbx
DeliverFileToBox:
  <<: *deliver_file_defaults
  args: box
DeliverFileToGoogleDrive:
  <<: *deliver_file_defaults
  args: gdr
DeliverFileToFTP:
  <<: *deliver_file_defaults
  args: ftp
DeliverFileToKnowings:
  <<: *deliver_file_defaults
  args: kwg
DeliverFileToMcf:
  <<: *deliver_file_defaults
  args: mcf

## Bridge ##

Bridge::RefreshAllUsersItemsWorker:
  queue: bridge
  cron: 0 */4 * * *


Bridge::RefreshAllUsersTransactionsWorker:
  queue: bridge
  cron: 0 */2 * * *

## Cedricom ##

Cedricom::GetListWorker:
  queue: cedricom
  cron: 0 12 * * *

Cedricom::FetchReceptionsWorker:
  queue: cedricom
  cron: 0 13 * * *

Cedricom::ImportTransactionsWorker:
  queue: cedricom
  cron: 0 14 * * *

Cedricom::ReconciliateOrphansWorker:
  queue: cedricom
  cron: 0 15 * * *

## Jedeclare ##

Jedeclare::GetListWorker:
  queue: cedricom
  cron: 0 12 * * *

Jedeclare::FetchReceptionsWorker:
  queue: cedricom
  cron: 0 13 * * *

Jedeclare::ImportTransactionsWorker:
  queue: cedricom
  cron: 0 14 * * *

 ## Budgea ##

Retriever::FetchOperationsWorker:
  queue: default
  cron: 0 1 * * *